### ISSUE TITLE
Agregar embed de YouTube para ver #HackCodear desde la landing

### ISSUE THREAD

**Issue by joelalejandro** [SomosCodear/codear-hacktoberfest-site#7]
Agregamos un nuevo reproductor en donde actualmente está la fecha del evento para que las personas que no pudieron ver la transmisión puedan hacerlo.

Diseño de referencia:
https://www.figma.com/file/YqX6xRHU2thQKrjXS39AoR/hack.codear.org-landing-post-evento?node-id=0%3A1

**Comment by asermax** [comment]
Closed by #8
